//GET http://localhost:4004/sap/opu/odata/sap/firstcapmodataAAA/api_sales_details/orderSet?$top=2


POST http://localhost:4004/sap/opu/odata/sap/firstcapmodataAAA/api_sales_details/orderSet
Content-Type: application/json

{
  "orderid"  : 8849, 
"customername" : "new Customer Post",
"contactperson" : "new contact person post",
"grossamount" : 8849,
"currency" : "USD"

}